create table contests (
 id bigint generated by default as identity primary key,
 title varchar(1000) not null, description text,
 type varchar(255) not null, category varchar(255) not null, region varchar(255) not null,
 district varchar(255), original_category varchar(255),
 start_date date not null, end_date date not null,
 place varchar(1000), eligibility varchar(1000), on_offline varchar(255) not null,
 original_url varchar(2000), image_url varchar(2000), fee varchar(255),
 source varchar(255) not null, source_id varchar(64) not null,
 created_at timestamptz not null, updated_at timestamptz not null,
 unique(source,source_id), check(end_date >= start_date)
);
create index idx_contest_region on contests(region);
create index idx_contest_category on contests(category);
create index idx_contest_end_date on contests(end_date);
create index idx_contest_region_end on contests(region,end_date);
create table app_users (
 id bigint generated by default as identity primary key,
 email varchar(254) not null unique, password varchar(255) not null, nickname varchar(40) not null,
 role varchar(255) not null, notification_frequency varchar(255) not null,
 reset_token varchar(64) unique, reset_token_expiry timestamptz,
 login_fail_count integer not null default 0, locked_until timestamptz, token_version integer not null default 0,
 created_at timestamptz not null, updated_at timestamptz not null
);
create table interest_categories (
 id bigint generated by default as identity primary key,
 user_id bigint not null references app_users(id) on delete cascade,
 category varchar(255) not null, unique(user_id,category)
);
create index idx_interest_category on interest_categories(category);
create table favorites (
 id bigint generated by default as identity primary key,
 user_id bigint not null references app_users(id) on delete cascade,
 contest_id bigint not null references contests(id) on delete cascade,
 created_at timestamptz not null, unique(user_id,contest_id)
);
create index idx_favorite_contest on favorites(contest_id);
create table notification_logs (
 id bigint generated by default as identity primary key,
 user_id bigint not null references app_users(id) on delete cascade,
 contest_id bigint not null references contests(id) on delete cascade,
 type varchar(255) not null, sent_at timestamptz, success boolean not null default false,
 unique(user_id,contest_id,type)
);
create index idx_notification_pending on notification_logs(type,success);
