alter table contests add column latitude double precision;
alter table contests add column longitude double precision;
alter table contests add column contact_phone varchar(255);
create table event_guides (
 id bigint generated by default as identity primary key,
 contest_id bigint not null references contests(id) on delete cascade,
 language varchar(10) not null,
 title varchar(1000), description text, place varchar(1000), fee varchar(1000), eligibility varchar(1000),
 transit text, parking text, booking text, accessibility text,
 contact_phone varchar(255), contact_email varchar(254), address varchar(1000),
 latitude double precision, longitude double precision,
 gallery text, video_id varchar(11), attribution varchar(1000), source_url varchar(2000),
 updated_by bigint not null references app_users(id), updated_at timestamptz not null,
 unique(contest_id,language),
 check (latitude between -90 and 90), check (longitude between -180 and 180),
 check ((latitude is null) = (longitude is null))
);
create table event_reviews (
 id bigint generated by default as identity primary key,
 contest_id bigint not null references contests(id) on delete cascade,
 user_id bigint not null references app_users(id) on delete cascade,
 rating integer not null check(rating between 1 and 5), body varchar(2000) not null,
 status varchar(20) not null default 'PENDING',
 version bigint not null default 0,
 created_at timestamptz not null, updated_at timestamptz not null,
 unique(contest_id,user_id)
);
create index idx_review_event_status on event_reviews(contest_id,status,created_at desc);
create index idx_review_moderation on event_reviews(status,created_at);
